# Generated by Django 4.1.1 on 2022-11-09 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_is_listing_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watch_list_users',
            field=models.ManyToManyField(related_name='watch_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
