# Generated by Django 4.1.1 on 2022-10-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_image_alter_listing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='Blank', max_length=64),
            preserve_default=False,
        ),
    ]
